# Generated by Django 5.1 on 2025-09-12 09:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('secret', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('events', models.JSONField(blank=True, null=True)),
                ('headers_json', models.JSONField(blank=True, null=True)),
                ('include_partials', models.BooleanField(default=False)),
                ('retry_enabled', models.BooleanField(default=True)),
                ('max_retries', models.IntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('successful_deliveries', models.IntegerField(default=0)),
                ('failed_deliveries', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(default='submission.created', max_length=50)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('dlq', 'Dead Letter Queue')], default='pending', max_length=20)),
                ('attempt', models.IntegerField(default=1)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('payload_size', models.IntegerField(default=0)),
                ('partial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.partial')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.submission')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_headers', models.JSONField()),
                ('request_body', models.TextField()),
                ('response_status', models.IntegerField(null=True)),
                ('response_headers', models.JSONField(null=True)),
                ('response_body', models.TextField(null=True)),
                ('error_message', models.TextField(null=True)),
                ('duration_ms', models.IntegerField(null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='webhooks.delivery')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeadLetterQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('payload_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redriven_at', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dlq_entry', to='webhooks.delivery')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='webhooks_de_created_d7f14b_idx'), models.Index(fields=['redriven_at'], name='webhooks_de_redrive_8cbf92_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'next_retry_at'], name='webhooks_de_status_546645_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['webhook', 'created_at'], name='webhooks_de_webhook_b47bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'created_at'], name='webhooks_de_status_b31920_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['delivery', 'attempt'], name='webhooks_we_deliver_4b52e9_idx'),
        ),
    ]
