version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: forms_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: forms_user
      POSTGRES_PASSWORD: forms_password
      POSTGRES_DB: forms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - forms_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forms_user -d forms_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: forms_redis
    ports:
      - "6379:6379"
    networks:
      - forms_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ClickHouse for analytics (production-ready)
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: forms_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: forms_analytics
      CLICKHOUSE_USER: forms_user
      CLICKHOUSE_PASSWORD: forms_password
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - forms_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  clickhouse_data:

networks:
  forms_network:
    driver: bridge
