version: "3.8"

services:
  ingest:
    build: .
    ports:
      - "8001:8001"
    environment:
      - DEBUG=true
      - HMAC_SECRET=dev-hmac-secret-change-in-production
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://forms_user:secure_password@postgres:5432/forms_db
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    command: python main.py

  worker:
    build: .
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql://forms_user:secure_password@postgres:5432/forms_db
      - INTERNAL_API_KEY=internal-worker-key
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    command: celery -A worker worker --loglevel=info --queue=submissions,webhooks,analytics

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=forms_db
      - POSTGRES_USER=forms_user
      - POSTGRES_PASSWORD=secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  redis_data:
  postgres_data:
