# Generated by Django 5.1 on 2025-09-12 09:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('pages', models.JSONField(blank=True, help_text='Form pages with blocks', null=True)),
                ('logic', models.JSONField(blank=True, help_text='Form logic rules', null=True)),
                ('theme', models.JSONField(blank=True, help_text='Form theme configuration', null=True)),
                ('settings', models.JSONField(blank=True, help_text='Form settings', null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('default_locale', models.CharField(default='en', max_length=10)),
                ('locales', models.JSONField(blank=True, null=True)),
                ('translations', models.JSONField(blank=True, null=True)),
                ('submission_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('schema', models.JSONField(help_text='Form schema at this version')),
                ('theme', models.JSONField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('canary_percentage', models.IntegerField(default=0, help_text='Percentage of traffic for canary deployment')),
                ('changelog', models.TextField(blank=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='forms.form')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['organization', 'status'], name='forms_form_organiz_6bb6ad_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['slug'], name='forms_form_slug_64e4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['-created_at'], name='forms_form_created_189000_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='form',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='formversion',
            index=models.Index(fields=['form', '-version'], name='forms_formv_form_id_8f4c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='formversion',
            index=models.Index(fields=['published_at'], name='forms_formv_publish_f5b332_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formversion',
            unique_together={('form', 'version')},
        ),
    ]
