version: '3.8'

services:
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./scripts/start_celery_worker.sh
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - POSTGRES_URL=postgresql://forms:forms_local_dev@postgres:5432/forms
      - REDIS_URL=redis://redis:6379/1
      - CELERY_CONCURRENCY=4
      - CELERY_QUEUES=default,webhooks,integrations
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    networks:
      - forms-network

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./scripts/start_celery_beat.sh
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - POSTGRES_URL=postgresql://forms:forms_local_dev@postgres:5432/forms
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    networks:
      - forms-network

networks:
  forms-network:
    external: true