import { DesignSettings } from "./DesignPanel";

export type ThemeCategory =
  | "all"
  | "professional"
  | "lead-generation"
  | "feedback"
  | "registration"
  | "onboarding"
  | "quizzes";

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  category: ThemeCategory;
  designSettings: DesignSettings;
}

export const THEME_CATEGORIES: { value: ThemeCategory; label: string }[] = [
  { value: "all", label: "All" },
  { value: "professional", label: "Professional" },
  { value: "lead-generation", label: "Lead Generation" },
  { value: "onboarding", label: "Onboarding" },
  { value: "feedback", label: "Feedback" },
  { value: "registration", label: "Registration" },
  { value: "quizzes", label: "Quizzes" },
];

export const THEME_PRESETS: ThemePreset[] = [
  // ============================================
  // PROFESSIONAL / BUSINESS (6 themes)
  // ============================================
  {
    id: "corporate-blue",
    name: "Corporate Blue",
    description: "Clean professional look for business forms",
    category: "professional",
    designSettings: {
      colors: {
        background: "#f8fafc",
        questions: "#1e293b",
        answers: "#475569",
        buttons: "#2563eb",
        buttonText: "#ffffff",
        starRating: "#2563eb",
      },
      alignment: "left",
      font: "Inter",
      fontSize: "medium",
      cornerStyle: "rounded",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "executive-dark",
    name: "Executive Dark",
    description: "Sophisticated dark theme for premium brands",
    category: "professional",
    designSettings: {
      colors: {
        background: "#1a1a2e",
        questions: "#ffffff",
        answers: "#a0aec0",
        buttons: "#6366f1",
        buttonText: "#ffffff",
        starRating: "#6366f1",
      },
      alignment: "center",
      font: "Plus Jakarta Sans",
      fontSize: "medium",
      cornerStyle: "normal",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "minimal-white",
    name: "Minimal White",
    description: "Ultra-clean minimal design",
    category: "professional",
    designSettings: {
      colors: {
        background: "#ffffff",
        questions: "#111827",
        answers: "#6b7280",
        buttons: "#111827",
        buttonText: "#ffffff",
        starRating: "#111827",
      },
      alignment: "left",
      font: "DM Sans",
      fontSize: "small",
      cornerStyle: "square",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "warm-professional",
    name: "Warm Professional",
    description: "Friendly and approachable business style",
    category: "professional",
    designSettings: {
      colors: {
        background: "#fffbeb",
        questions: "#78350f",
        answers: "#92400e",
        buttons: "#d97706",
        buttonText: "#ffffff",
        starRating: "#d97706",
      },
      alignment: "left",
      font: "Nunito",
      fontSize: "medium",
      cornerStyle: "rounded",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "tech-startup",
    name: "Tech Startup",
    description: "Modern tech vibe with dark aesthetics",
    category: "professional",
    designSettings: {
      colors: {
        background: "#0f172a",
        questions: "#f1f5f9",
        answers: "#94a3b8",
        buttons: "#06b6d4",
        buttonText: "#ffffff",
        starRating: "#06b6d4",
      },
      alignment: "center",
      font: "Space Grotesk",
      fontSize: "medium",
      cornerStyle: "very_rounded",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "legal-finance",
    name: "Legal & Finance",
    description: "Trustworthy and serious for formal contexts",
    category: "professional",
    designSettings: {
      colors: {
        background: "#fafafa",
        questions: "#18181b",
        answers: "#52525b",
        buttons: "#0f766e",
        buttonText: "#ffffff",
        starRating: "#0f766e",
      },
      alignment: "left",
      font: "Libre Baskerville",
      fontSize: "medium",
      cornerStyle: "normal",
      backgroundImage: null,
      logo: null,
    },
  },

  // ============================================
  // LEAD GENERATION (5 themes)
  // ============================================
  {
    id: "high-convert",
    name: "High Convert",
    description: "Bold CTA focused design for maximum conversions",
    category: "lead-generation",
    designSettings: {
      colors: {
        background: "#ffffff",
        questions: "#1f2937",
        answers: "#4b5563",
        buttons: "#dc2626",
        buttonText: "#ffffff",
        starRating: "#dc2626",
      },
      alignment: "center",
      font: "Poppins",
      fontSize: "large",
      cornerStyle: "very_rounded",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "friendly-lead",
    name: "Friendly Lead",
    description: "Warm and approachable for higher engagement",
    category: "lead-generation",
    designSettings: {
      colors: {
        background: "#fef3c7",
        questions: "#92400e",
        answers: "#b45309",
        buttons: "#f59e0b",
        buttonText: "#ffffff",
        starRating: "#f59e0b",
      },
      alignment: "center",
      font: "Nunito",
      fontSize: "medium",
      cornerStyle: "very_rounded",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "saas-growth",
    name: "SaaS Growth",
    description: "Modern SaaS style for software products",
    category: "lead-generation",
    designSettings: {
      colors: {
        background: "#f0fdf4",
        questions: "#166534",
        answers: "#15803d",
        buttons: "#22c55e",
        buttonText: "#ffffff",
        starRating: "#22c55e",
      },
      alignment: "left",
      font: "Inter",
      fontSize: "medium",
      cornerStyle: "rounded",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "premium-lead",
    name: "Premium Lead",
    description: "Luxury feel for high-value prospects",
    category: "lead-generation",
    designSettings: {
      colors: {
        background: "#1c1917",
        questions: "#fafaf9",
        answers: "#a8a29e",
        buttons: "#ca8a04",
        buttonText: "#ffffff",
        starRating: "#ca8a04",
      },
      alignment: "center",
      font: "Playfair Display",
      fontSize: "large",
      cornerStyle: "normal",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "giveaway-fun",
    name: "Giveaway Fun",
    description: "Exciting and playful for contests and giveaways",
    category: "lead-generation",
    designSettings: {
      colors: {
        background: "#fdf4ff",
        questions: "#86198f",
        answers: "#a21caf",
        buttons: "#d946ef",
        buttonText: "#ffffff",
        starRating: "#d946ef",
      },
      alignment: "center",
      font: "Outfit",
      fontSize: "large",
      cornerStyle: "very_rounded",
      backgroundImage: null,
      logo: null,
    },
  },

  // ============================================
  // CLIENT INTAKE & ONBOARDING (5 themes)
  // ============================================
  {
    id: "client-welcome",
    name: "Client Welcome",
    description: "Warm and professional for client intake",
    category: "onboarding",
    designSettings: {
      colors: {
        background: "#f5f5f4",
        questions: "#292524",
        answers: "#57534e",
        buttons: "#0891b2",
        buttonText: "#ffffff",
        starRating: "#0891b2",
      },
      alignment: "left",
      font: "Lato",
      fontSize: "medium",
      cornerStyle: "rounded",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "healthcare-intake",
    name: "Healthcare Intake",
    description: "Clean and trustworthy for medical forms",
    category: "onboarding",
    designSettings: {
      colors: {
        background: "#f0fdfa",
        questions: "#134e4a",
        answers: "#115e59",
        buttons: "#14b8a6",
        buttonText: "#ffffff",
        starRating: "#14b8a6",
      },
      alignment: "left",
      font: "Open Sans",
      fontSize: "medium",
      cornerStyle: "rounded",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "legal-intake",
    name: "Legal Intake",
    description: "Formal and structured for legal services",
    category: "onboarding",
    designSettings: {
      colors: {
        background: "#fafaf9",
        questions: "#1c1917",
        answers: "#44403c",
        buttons: "#57534e",
        buttonText: "#ffffff",
        starRating: "#57534e",
      },
      alignment: "left",
      font: "Merriweather",
      fontSize: "medium",
      cornerStyle: "normal",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "agency-onboard",
    name: "Agency Onboard",
    description: "Creative and professional for agencies",
    category: "onboarding",
    designSettings: {
      colors: {
        background: "#faf5ff",
        questions: "#581c87",
        answers: "#7e22ce",
        buttons: "#a855f7",
        buttonText: "#ffffff",
        starRating: "#a855f7",
      },
      alignment: "left",
      font: "Manrope",
      fontSize: "medium",
      cornerStyle: "rounded",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "saas-onboarding",
    name: "SaaS Onboarding",
    description: "Modern product onboarding experience",
    category: "onboarding",
    designSettings: {
      colors: {
        background: "#eff6ff",
        questions: "#1e3a8a",
        answers: "#3b82f6",
        buttons: "#2563eb",
        buttonText: "#ffffff",
        starRating: "#2563eb",
      },
      alignment: "center",
      font: "Inter",
      fontSize: "medium",
      cornerStyle: "very_rounded",
      backgroundImage: null,
      logo: null,
    },
  },

  // ============================================
  // FEEDBACK & SURVEYS (5 themes)
  // ============================================
  {
    id: "customer-voice",
    name: "Customer Voice",
    description: "Friendly and inviting for feedback collection",
    category: "feedback",
    designSettings: {
      colors: {
        background: "#ecfdf5",
        questions: "#065f46",
        answers: "#047857",
        buttons: "#10b981",
        buttonText: "#ffffff",
        starRating: "#10b981",
      },
      alignment: "left",
      font: "Nunito",
      fontSize: "medium",
      cornerStyle: "rounded",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "nps-survey",
    name: "NPS Survey",
    description: "Clean and neutral for NPS surveys",
    category: "feedback",
    designSettings: {
      colors: {
        background: "#f9fafb",
        questions: "#111827",
        answers: "#4b5563",
        buttons: "#6366f1",
        buttonText: "#ffffff",
        starRating: "#6366f1",
      },
      alignment: "center",
      font: "Inter",
      fontSize: "small",
      cornerStyle: "rounded",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "product-feedback",
    name: "Product Feedback",
    description: "Tech product style for feature feedback",
    category: "feedback",
    designSettings: {
      colors: {
        background: "#f8fafc",
        questions: "#0f172a",
        answers: "#475569",
        buttons: "#8b5cf6",
        buttonText: "#ffffff",
        starRating: "#8b5cf6",
      },
      alignment: "left",
      font: "DM Sans",
      fontSize: "medium",
      cornerStyle: "rounded",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "demo-feedback",
    name: "Demo Feedback",
    description: "Engaging style for demo and trial feedback",
    category: "feedback",
    designSettings: {
      colors: {
        background: "#fefce8",
        questions: "#713f12",
        answers: "#a16207",
        buttons: "#eab308",
        buttonText: "#ffffff",
        starRating: "#eab308",
      },
      alignment: "center",
      font: "Work Sans",
      fontSize: "medium",
      cornerStyle: "rounded",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "cancellation-survey",
    name: "Cancellation Survey",
    description: "Soft and understanding for churn surveys",
    category: "feedback",
    designSettings: {
      colors: {
        background: "#fef2f2",
        questions: "#7f1d1d",
        answers: "#991b1b",
        buttons: "#ef4444",
        buttonText: "#ffffff",
        starRating: "#ef4444",
      },
      alignment: "center",
      font: "Lato",
      fontSize: "medium",
      cornerStyle: "rounded",
      backgroundImage: null,
      logo: null,
    },
  },

  // ============================================
  // EVENT & REGISTRATION (4 themes)
  // ============================================
  {
    id: "event-signup",
    name: "Event Signup",
    description: "Exciting and energetic for event registration",
    category: "registration",
    designSettings: {
      colors: {
        background: "#fff7ed",
        questions: "#9a3412",
        answers: "#c2410c",
        buttons: "#f97316",
        buttonText: "#ffffff",
        starRating: "#f97316",
      },
      alignment: "center",
      font: "Poppins",
      fontSize: "large",
      cornerStyle: "very_rounded",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "workshop-register",
    name: "Workshop Register",
    description: "Educational and calm for workshops",
    category: "registration",
    designSettings: {
      colors: {
        background: "#f0f9ff",
        questions: "#0c4a6e",
        answers: "#0369a1",
        buttons: "#0ea5e9",
        buttonText: "#ffffff",
        starRating: "#0ea5e9",
      },
      alignment: "left",
      font: "Open Sans",
      fontSize: "medium",
      cornerStyle: "rounded",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "hackathon",
    name: "Hackathon",
    description: "Tech and bold for hackathon events",
    category: "registration",
    designSettings: {
      colors: {
        background: "#18181b",
        questions: "#fafafa",
        answers: "#a1a1aa",
        buttons: "#22d3ee",
        buttonText: "#18181b",
        starRating: "#22d3ee",
      },
      alignment: "center",
      font: "JetBrains Mono",
      fontSize: "medium",
      cornerStyle: "square",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "yoga-wellness",
    name: "Yoga & Wellness",
    description: "Zen and peaceful for wellness events",
    category: "registration",
    designSettings: {
      colors: {
        background: "#f5f5f4",
        questions: "#44403c",
        answers: "#78716c",
        buttons: "#84cc16",
        buttonText: "#ffffff",
        starRating: "#84cc16",
      },
      alignment: "center",
      font: "Raleway",
      fontSize: "medium",
      cornerStyle: "very_rounded",
      backgroundImage: null,
      logo: null,
    },
  },

  // ============================================
  // QUIZZES & FUN (5 themes)
  // ============================================
  {
    id: "personality-quiz",
    name: "Personality Quiz",
    description: "Fun and vibrant for personality tests",
    category: "quizzes",
    designSettings: {
      colors: {
        background: "#fdf2f8",
        questions: "#9d174d",
        answers: "#be185d",
        buttons: "#ec4899",
        buttonText: "#ffffff",
        starRating: "#ec4899",
      },
      alignment: "center",
      font: "Outfit",
      fontSize: "large",
      cornerStyle: "very_rounded",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "knowledge-test",
    name: "Knowledge Test",
    description: "Educational style for knowledge assessments",
    category: "quizzes",
    designSettings: {
      colors: {
        background: "#fffbeb",
        questions: "#78350f",
        answers: "#b45309",
        buttons: "#f59e0b",
        buttonText: "#ffffff",
        starRating: "#f59e0b",
      },
      alignment: "center",
      font: "Poppins",
      fontSize: "medium",
      cornerStyle: "rounded",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "marketing-quiz",
    name: "Marketing Quiz",
    description: "Professional fun for marketing assessments",
    category: "quizzes",
    designSettings: {
      colors: {
        background: "#f0fdf4",
        questions: "#14532d",
        answers: "#166534",
        buttons: "#22c55e",
        buttonText: "#ffffff",
        starRating: "#22c55e",
      },
      alignment: "center",
      font: "Montserrat",
      fontSize: "large",
      cornerStyle: "rounded",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "trivia-game",
    name: "Trivia Game",
    description: "Playful and bold for trivia quizzes",
    category: "quizzes",
    designSettings: {
      colors: {
        background: "#eef2ff",
        questions: "#3730a3",
        answers: "#4f46e5",
        buttons: "#6366f1",
        buttonText: "#ffffff",
        starRating: "#6366f1",
      },
      alignment: "center",
      font: "Space Grotesk",
      fontSize: "large",
      cornerStyle: "very_rounded",
      backgroundImage: null,
      logo: null,
    },
  },
  {
    id: "assessment",
    name: "Assessment",
    description: "Serious but engaging for professional assessments",
    category: "quizzes",
    designSettings: {
      colors: {
        background: "#f8fafc",
        questions: "#1e293b",
        answers: "#475569",
        buttons: "#0d9488",
        buttonText: "#ffffff",
        starRating: "#0d9488",
      },
      alignment: "left",
      font: "Inter",
      fontSize: "medium",
      cornerStyle: "rounded",
      backgroundImage: null,
      logo: null,
    },
  },
];
