# Generated by Django 5.1 on 2025-09-12 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partial',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partials', to='forms.form'),
        ),
        migrations.AddField(
            model_name='submission',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.form'),
        ),
        migrations.AddField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.submission'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'organization')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'created_at'], name='core_auditl_organiz_c79039_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity', 'entity_id'], name='core_auditl_entity_d1c59f_idx'),
        ),
        migrations.AddIndex(
            model_name='partial',
            index=models.Index(fields=['updated_at'], name='core_partia_updated_d708de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partial',
            unique_together={('form', 'respondent_key')},
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['form', 'completed_at'], name='core_submis_form_id_f08160_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['respondent_key'], name='core_submis_respond_642a3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('submission', 'block_id')},
        ),
    ]
